# SLAM Planner can be used either GMapping or static maps as they both provide
# SLAM strategies, see the related proc modules configurations.
hbba_conf:
# This proc module's role is only to provide variable input filtering to the
# move_base behavior.
# It doesn't actually process anything.
- behavior:
    name: interaction
    launch: {pkg: 'recep', path: 'launch/recep_behavior.launch'}
    priority: 10
    input:
      - camera_image

    output:
      - face

            
- strat:
    name: InteractionPlanner
    class: Interaction
    utility: 8
    modules:
        - interaction

