hbba_conf:

# WARNING: Not up to date with Melodic / TB3 config (2019/09)

# This proc module includes a static map server and an amcl localization node to
# replicate the features of turtlebot_proc_slam_gmapping.

- procmodule:
    name: vision
    launch: {pkg: 'recep', path: 'launch/recep_proc.launch'}
    input:
      - camera_image

    output:
      - face
